import Background from '@/components/Background/Background'
import CartBar from '@/components/CartBar/CartBar'
import { CartProvider } from '@/context/card.context'
import Header from '@/components/Header/Header'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.css'

const inter = Quicksand({
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='relative'>
			<body className={inter.className}>
				<CartProvider>
					<CartBar />
					<Background />
					<Header />
					<main>{children}</main>
				</CartProvider>
			</body>
		</html>
	)
}
