import Header from '@/components/Header/Header'
// import { auth } from '@/utils/getSession'
import type { Metadata } from 'next'
import './globals.css'

import { Quicksand } from 'next/font/google'
import Background from '@/components/Background/Background'

const inter = Quicksand({
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	// const session = await auth()

	return (
		<html lang='en' className='relative'>
			<body className={inter.className}>
				<Background />
				<Header />
				<main>{children}</main>
			</body>
		</html>
	)
}
